### ISSUE TITLE
请教一下 苹果cms对接tvbox的json地址怎么配置？

### ISSUE THREAD

**Issue by ErDongChen1973** [feg545/maccms10-tvbox-api#1]

**Comment by feg545** [comment]
可以在 https://github.com/gaotianliuyun/gao  这个里面找一些tvbox配置文件进行参考。
主要是sites配置里面添加一段，格式如下：
```
{
      "key": "apple",
      "name": "🍎苹果影院",
      "type": 1,
      "api": "http://192.168.8.8:8080/api.php/tvbox",
      "searchable": 1,
      "quickSearch": 1,
      "filterable": 1
    }
```

**Comment by feg545** [comment]
这里有一个tvbox配置文件编辑器，可以试试
https://catvodtvofficial.github.io/CatVodTVJsonEditor/

**Comment by ErDongChen1973** [comment]
> 这里有一个tvbox配置文件编辑器，可以试试
> https://catvodtvofficial.github.io/CatVodTVJsonEditor/

好的👌🏻  谢谢！

**Comment by yantouer** [comment]
请问文中提到的TVBOX里面配置相应的接口即可。这个接口该怎么配置。

**Comment by ErDongChen1973** [comment]
> 请问文中提到的TVBOX里面配置相应的接口即可。这个接口该怎么配置。
 你去找一个别人的配置文件（直接用浏览器打开能看到代码的那种），可以看到里面的很多源就是用的就是cms的接口，你直接把别人的源文件保存到本地，然后你再加一条你自己的，就可以了
![Screenshot_2024-01-31-12-46-34-179_com.hiker.youtoo-edit.jpg](https://github.com/feg545/maccms10-tvbox-api/assets/44294575/81426b4e-9bf4-4b00-b1a9-859d285066c2)

**Comment by feg545** [comment]
你先试试在线编辑器 https://catvodtvofficial.github.io/CatVodTVJsonEditor/ 学习一下配置文件格式，
就挺简单的啊，在json文件sites里面加一段就好了
